require: rubocop-rails
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'node_modules/**/*'
    - 'spec/dummy/node_modules/**/*'
    - 'spec/dummy/db/schema.rb'
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
